### ISSUE TITLE
spark history server 

### ISSUE THREAD

**Issue by luck02** [apache-spark-on-k8s/spark#387]
Wondering if anyone has considered this use case:
https://spark.apache.org/docs/2.1.0/monitoring.html#viewing-after-the-fact

Presumable you'd want to deploy a history server like the resource server or shuffle service.  And we'd want to have a way to configure jobs to leave their event logs somewhere.

Has anyone thought about this, in an ideal world I'd like to contribute this.  

The history server is really quite important for the k8s / spark story as it looks like the intention is a short lived cluster / job.  So we'd need a way to inspect the UI after job has executed (and blown up).

**Comment by foxish** [comment]
We had some discussions about this particular issue. I think @mccheah and @ifilonenko were interested in this item.

**Comment by erikerlandson** [comment]
cross-referencing #111

**Comment by mccheah** [comment]
@luck02 feel free to contribute something here. I'd imagine we can provide a YML specification along with a Docker image that can run the history server that reads event logs from storage that is shared between the history server and the jobs - typically an HDFS location. That's a very primitive way of managing the history server - there's a lot more advanced tooling that we can build such as linking to history server pages from the Kubernetes dashboard, but we should be able to come up with something fairly primitive in a relatively small changeset.

Exposing the live Spark UI while a job is running is a little harder because there isn't a great generic method to expose an arbitrary Spark driver pod outside of the cluster. Depending on the cluster's setup, there are options ranging from NodePort services to using an Ingress, but it's difficult for spark-submit to create the route to the backend pod in a generic manner. For that I would suggest building something on top of spark-submit that makes sense for your specific environment.

**Comment by duyanghao** [comment]
> That wouldn't work, unless that's running within the cluster. We need to write a deployment that launches the SHS within the cluster. Tracked in #387. Closing as dupe.

@foxish i start SHS outside of k8s cluster,and it works without spark logs as i mention in this [issue](https://github.com/apache-spark-on-k8s/spark/issues/443).

I am curious about whether there will be `spark logs` on SHS(same as `spark on yarn`) when deploy SHS within the cluster.

**Comment by AzureQ** [comment]
I did a very simple PoC try to get it work and documented it [here](https://azureq.gitbooks.io/data-experimenting-on-kubernetes/content/chapter1/enable-spark-history-server/experiment-deploy-spark-history-server-on-kubernetes.html)
To summarize:
1. Deploy an HDFS in the same k8s cluster or set up an accessible external HDFS(I tested with Dataproc cluster)
2. Use kubespark/spark-init image with a command taking log dir as a parameter
3. Run as a deployment in k8s.

**Comment by skonto** [comment]
Any progress on this? @AzureQ I tried to access the doc but it is not available.

**Comment by AzureQ** [comment]
@skonto Sorry, I was working on updating the content with Spark 2.3, check [here](https://azureq.gitbooks.io/data-on-kubernetes/content/chapter1/running-spark-on-gke.html), basically the idea is to use GCS/Amazon S3/Azure Blob Storage as the backend filesystem. There's another solution based on NFS:  using podpreset to mount same NFS to driver and history server, which removes the dependency on blobstore but harder to setup since podpreset is not enabled by default in most K8s service offering and also it seems to move under service-catalog nowadays.

**Comment by ihardzeenka** [comment]
For my project I used HDFS as storage for logs on Spark. HDFS deployment can be found here:
https://github.com/apache-spark-on-k8s/kubernetes-HDFS

Here is my sample Docker file:
```
FROM spark-base 
ENV SPARK_LOG_DIR /opt/spark/logs
RUN mkdir -p /opt/spark/logs
ENTRYPOINT [ "/opt/entrypoint.sh", "/opt/spark/bin/spark-class", "org.apache.spark.deploy.history.HistoryServer" , "--properties-file"]
```
Here is K8s yaml file:
```
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: spark-history-server
spec:
  replicas: 1
  template:
    metadata:
      labels:
        history-server-instance: default
    spec:
      volumes:
        - name: history-server-properties
          configMap:
            name: spark-history-server-config
      containers:
        - name: spark-history-server
          image: ihardz/history-server:latest
          resources:
            requests:
              cpu: 250m
              memory: 256Mi
            limits:
              cpu: 1000m
              memory: 1Gi
          volumeMounts:
            - name: history-server-properties
              mountPath: '/etc/spark-history-server'
          args:
            - '/etc/spark-history-server/history-server.properties'
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: spark-history-server-config
data:
  history-server.properties: |
    spark.history.fs.cleaner.enabled=true
    spark.history.fs.cleaner.interval=86400
    spark.history.fs.cleaner.maxAge=604800
    spark.history.fs.update.interval.seconds=10
    spark.history.retainedApplications=50
    spark.history.ui.port=18088
    spark.ssl.historyServer.enabled=false
    spark.ssl.historyServer.keyStore=
    spark.ssl.historyServer.port=18488
    spark.ssl.historyServer.protocol=TLSv1.2
    spark.port.maxRetries=0
    spark.history.fs.logDirectory=hdfs://hdfs-namenode-0.hdfs-namenode.hdfs.svc.cluster.local:8020/spark-event
    spark.history.kerberos.enabled=false
    spark.ui.filters=org.apache.spark.deploy.yarn.YarnProxyRedirectFilter
---
apiVersion: v1
kind: Service
metadata:
  name: spark-history-service
spec:
  selector:
    history-server-instance: default
  ports:
    - name: http
      protocol: TCP
      port: 18088
      targetPort: 18088
```
When running spark job through spark-submit you would need to set thhose 2 options:
```
spark.eventLog.enabled=true
spark.eventLog.dir=hdfs://hdfs-namenode-0.hdfs-namenode.hdfs.svc.cluster.local:8020/spark-event
```
Note: 
1) Idea is that spark.eventLog.dir = spark.history.fs.logDirectory
2) In my case I changed namespace to hdfs. In original HDFS scripts name node should be:
hdfs-namenode-0.hdfs-namenode.**default**.svc.cluster.local
