### ISSUE TITLE
Support setting ImagePullSecrets on the Spark pods

### ISSUE THREAD

**Issue by ash211** [apache-spark-on-k8s/spark#42]
For connecting to an authenticated docker registry where the underlying k8s cluster doesn't already have those docker creds, k8s supports specifying that registry's keys in a k8s secret and referring to the secret in the podspec.  We should support that in spark-on-k8s

Following docs at https://kubernetes.io/docs/user-guide/images/#specifying-imagepullsecrets-on-a-pod that looks like:

Create a secret:
- `$ kubectl create secret docker-registry myregistrykey --docker-server=DOCKER_REGISTRY_SERVER --docker-username=DOCKER_USER --docker-password=DOCKER_PASSWORD --docker-email=DOCKER_EMAIL`

Use the secret on a pod using `imagePullSecrets`:
```
apiVersion: v1
kind: Pod
metadata:
  name: foo
  namespace: awesomeapps
spec:
  containers:
    - name: foo
      image: janedoe/awesomeapp:v1
  imagePullSecrets:
    - name: myregistrykey
```

We need a way to specify the creds that are used to pull the Spark images from a docker registry.

This is probably additional support for using fully-customizable YAML for pod specs: https://github.com/apache-spark-on-k8s/spark/issues/38
